export const SET_NET_INFO = "SET_NET_INFO";

export const PRESENT_LOADER = "PRESENT_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const PRESENT_MODAL = "PRESENT_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const RESET_STORE = "RESET_STORE";

export const SET_TOKEN = "SET_TOKEN";
export const RESET_TOKEN = "RESET_TOKEN";
export const REFRESH_ACCESS_TOKEN = "REFRESH_ACCESS_TOKEN";

export const REFRESH_TOKEN_POST_API_REQUEST = "REFRESH_TOKEN_POST_API_REQUEST";
export const REFRESH_TOKEN_POST_API_SUCCESS = "REFRESH_TOKEN_POST_API_SUCCESS";
export const REFRESH_TOKEN_POST_API_FAILURE = "REFRESH_TOKEN_POST_API_FAILURE";

export const AUTH_TOKEN = "AUTH_TOKEN";
export const SET_ERROR = "SET_ERROR";
export const RESET_ERROR = "RESET_ERROR";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_USER = "SET_USER";
export const RESET_AUTH = "RESET_AUTH";

export const LOGIN_POST_API_REQUEST = "LOGIN_POST_API_REQUEST";
export const LOGIN_POST_API_SUCCESS = "LOGIN_POST_API_SUCCESS";
export const LOGIN_POST_API_FAILURE = "LOGIN_POST_API_FAILURE";

export const SET_SING_UP_INFORMATION = "SET_SING_UP_INFORMATION";

export const FORGOT_PASSWORD_POST_API_REQUEST =
  "FORGOT_PASSWORD_POST_API_REQUEST";
export const FORGOT_PASSWORD_POST_API_SUCCESS =
  "FORGOT_PASSWORD_POST_API_SUCCESS";
export const FORGOT_PASSWORD_POST_API_FAILURE =
  "FORGOT_PASSWORD_POST_API_FAILURE";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";

export const SET_DESTINATION_COUNTRY = "SET_DESTINATION_COUNTRY";
export const SET_SOURCE_COUNTRY = "SET_SOURCE_COUNTRY";
export const SET_ALL_COUNTRY = "SET_ALL_COUNTRY";

export const SET_EXCHANGE_RATE = "SET_EXCHANGE_RATE";
export const CLEAR_USER = "CLEAR_USER";

export const SET_SENDER_BANK = "SET_SENDER_BANK";
export const SET_SENDER_CARD = "SET_SENDER_CARD";

export const SET_BENEFICIARY = "GET_BENEFICIARY";
export const RECEIVER_PAYMENT_METHOD = "RECEIVER_PAYMENT_METHOD";

export const SENDER_PAYMENT_METHOD = "SENDER_PAYMENT_METHOD";

export const RECEIVER_INFORMATION = "RECEIVER_INFORMATION";
export const TRANSACTION_AMOUNT_DETAIL = "TRANSACTION_AMOUNT_DETAIL";

export const SENDER_TRANSACTION_LIMIT = "SENDER_TRANSACTION_LIMIT";
export const CLEAR_SENDER_TRANSACTION_LIMIT = "CLEAR_SENDER_TRANSACTION_LIMIT";
export const SET_TRANSFER_FEES = "SET_TRANSFER_FEES";

export const CLEAR_TRANSACTION_INFORMATION = "CLEAR_TRANSACTION_INFORMATION";
export const GET_ALL_TRANSACTON = "GET_ALL_TRANSACTON";

export const CLEAR_PAYMENT_DETAIL = "CLEAR_PAYMENT_DETAIL";
export const CLEAR_SENDER_PAYMENT_DETAIL = "CLEAR_SENDER_PAYMENT_DETAIL";
export const CLEAR_RECEIVER_PAYMENT_DETAIL = "CLEAR_RECEIVER_PAYMENT_DETAIL";
export const GET_ACTIVE_ACCOUNT_PAGE = "GET_ACTIVE_ACCOUNT_PAGE";
export const GET_ACTIVE_ACCOUNT_SIDE_BAR = "GET_ACTIVE_ACCOUNT_SIDE_BAR";
export const GET_SELECTED_PAYOUT_METHOD = "GET_SELECTED_PAYOUT_METHOD";

export const SET_US_STATES = "SET_US_STATES";
export const SET_NGA_STATES = "SET_NGA_STATES";

export const SET_FEE_STRUCTURE = "SET_FEE_STRUCTURE";
export const SET_UNLOCKED_SENDER = "SET_UNLOCKED_SENDER";
export const ACCEPT_POLICY = "ACCEPT_POLICY";
